# Generated by Django 3.0.3 on 2020-04-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_sqlitestat1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mediatypes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playlists',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'managed': True},
        ),
    ]
