# Generated by Django 3.0.3 on 2020-04-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200421_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='albums',
            name='artistid',
            field=models.ForeignKey(db_column='ArtistId', on_delete=django.db.models.deletion.CASCADE, to='api.Artists'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(db_column='Title', max_length=160),
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='company',
            field=models.CharField(blank=True, db_column='Company', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(db_column='Email', max_length=160),
        ),
        migrations.AlterField(
            model_name='customers',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='firstname',
            field=models.CharField(db_column='FirstName', max_length=160),
        ),
        migrations.AlterField(
            model_name='customers',
            name='lastname',
            field=models.CharField(db_column='LastName', max_length=160),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='postalcode',
            field=models.CharField(blank=True, db_column='PostalCode', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(blank=True, db_column='State', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='supportrepid',
            field=models.ForeignKey(db_column='SupportRepId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.CharField(db_column='FirstName', max_length=160),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.CharField(db_column='LastName', max_length=160),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='postalcode',
            field=models.CharField(blank=True, db_column='PostalCode', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='state',
            field=models.CharField(blank=True, db_column='State', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(db_column='Name', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoiceid',
            field=models.ForeignKey(db_column='InvoiceId', on_delete=django.db.models.deletion.CASCADE, to='api.Invoices'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='unitprice',
            field=models.CharField(db_column='UnitPrice', max_length=160),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='billingaddress',
            field=models.CharField(blank=True, db_column='BillingAddress', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='billingcity',
            field=models.CharField(blank=True, db_column='BillingCity', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='billingcountry',
            field=models.CharField(blank=True, db_column='BillingCountry', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='billingpostalcode',
            field=models.CharField(blank=True, db_column='BillingPostalCode', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='billingstate',
            field=models.CharField(blank=True, db_column='BillingState', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.PROTECT, to='api.Customers'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total',
            field=models.CharField(db_column='Total', max_length=160),
        ),
        migrations.AlterField(
            model_name='mediatypes',
            name='name',
            field=models.CharField(db_column='Name', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='name',
            field=models.CharField(db_column='Name', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlistid',
            field=models.ForeignKey(db_column='PlaylistId', on_delete=django.db.models.deletion.CASCADE, to='api.Playlists'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='trackid',
            field=models.ForeignKey(db_column='TrackId', on_delete=django.db.models.deletion.CASCADE, to='api.Tracks'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='albumid',
            field=models.ForeignKey(db_column='AlbumId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Albums'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='composer',
            field=models.CharField(blank=True, db_column='Composer', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='genreid',
            field=models.ForeignKey(db_column='GenreId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Genres'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='mediatypeid',
            field=models.ForeignKey(db_column='MediaTypeId', on_delete=django.db.models.deletion.CASCADE, to='api.MediaTypes'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='name',
            field=models.CharField(db_column='Name', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='unitprice',
            field=models.CharField(db_column='UnitPrice', max_length=160),
        ),
    ]
