# Generated by Django 3.0.3 on 2020-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200421_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
