# Generated by Django 3.0.3 on 2020-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200421_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='id',
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='bid',
            field=models.AutoField(db_column='BID', default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
