# Generated by Django 3.0.3 on 2020-04-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200421_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='bid',
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlistid',
            field=models.ForeignKey(db_column='PlaylistId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Playlists'),
        ),
    ]
